// format.js — port of the VBA Sub EDUFiller (Module1 L9527–10223).
//
// Takes the DataRow[] produced by compute() plus the project's header
// lines, and emits the full EDU file as a single string.
//
// Each unit block:
//
//   ; COMMENTS              <unit name / soldier / start-exp ...>
//   type                    <type>
//   dictionary              <dict>
//   category                <cat>
//   class                   <class>
//   voice_type              <voice>
//   voice_indexes           <indexes>
//   soldier[s]              <model>, <men>, <extras>, <mass>
//   [{ default { model1 model2 ... } }]            ← when unit variation > 0
//   officer                 <model>                ← 0–5 officer lines
//   ship/engine/animal/mount <id>                  ← one of, category-dependent
//   attributes              flag1, flag2, ...
//   formation               <hr cl>, <vr cl>, <hr ls>, <vr ls>, <ranks>, <f1>[, <f2>]
//   stat_health             <hp>, <sec hp>
//   stat_pri                <attack>, <charge>, <msl>, <range>, <ammo>, <wpn>, <tech>, <dmg>, <snd>, <min>, <leth>
//   stat_pri_attr           <flags>
//   stat_sec                <same pattern>
//   stat_sec_attr           <flags>
//   stat_pri_armour         <armour>, <defence>, <shield>, <hit sound>
//   stat_sec_armour         <sec armour>, <sec defence>, <sec hit sound>
//   stat_heat               <heat>
//   stat_ground             <scrub>, <sand>, <forest>, <snow>
//   stat_mental             <morale>, <discipline>, <training>
//   stat_charge_dist        <dist>
//   stat_fire_delay         <delay>
//   stat_food               <food1>, <food2>
//   stat_cost               <turns>, <price>, <upkeep>, <wpn_upg>, <arm_upg>, <cb_cost>
//   recruit_priority_offset <prio>
//   ownership               <faction>, <faction>, ..., slave
//
// Comment rows → "; <text>" framed by blank lines.
// WIP rows → skipped.


const KEY_PAD = 24;    // width of the keyword column in EDU files

function line(key, value) {
  const k = String(key || "");
  if (value === undefined || value === null || value === "") return k;
  const pad = Math.max(1, KEY_PAD - k.length);
  return k + " ".repeat(pad) + value;
}

/** Pad a lone keyword (no value) to the 24-char column, matching what VBA
 *  emits for soldier-block bracket/default lines. */
function pad24(key) {
  const k = String(key);
  return k + " ".repeat(Math.max(0, KEY_PAD - k.length));
}

function joinCSV(parts) {
  return parts.filter((p) => p !== null && p !== undefined && p !== "").join(", ");
}

function fmtNum(n, decimals) {
  if (typeof n !== "number" || !Number.isFinite(n)) return "";
  if (Number.isInteger(n)) return String(n);
  // Round off float-precision fuzz and trim trailing zeros. 2 decimals is
  // sufficient for mass / spacing / lethality / formation values.
  const d = decimals != null ? decimals : 2;
  return (Math.round(n * 10 ** d) / 10 ** d).toString();
}

/** Build the EDU preamble (VBA EDUmation2 L10224–10298). */
function buildPreamble(project, headerLines) {
  const out = [];
  out.push(";Generated by the EDU-matic, created by Aradan for Norman Invasion");
  out.push(";Please visit http://www.twcenter.net/forums/showthread.php?t=111344 for Aradan's Complete EDU Guide");
  out.push(";Free to use as long as this header is kept in place. Thank you.");
  out.push(`;EDU for ${project.modInfo?.name || ""}...`);
  out.push("");
  out.push("");
  for (const h of (headerLines || [])) out.push(h || "");
  out.push("");
  out.push("");
  out.push("");
  out.push("");
  out.push("");
  out.push("; ACTUAL EDU STARTS HERE");
  out.push("");
  out.push("");
  return out;
}

/** Format a single DATA comment row as a standalone EDU comment block.
 *  VBA EDUFiller frames `; <text>` with 2 blanks before + 2 blanks after
 *  the comment line. The unit loop already pushes 1 trailing blank after
 *  the previous unit block, so we contribute 1 leading blank + comment +
 *  2 trailing blanks. The next unit's "; COMMENTS" line follows directly,
 *  giving the desired blank/blank/comment/blank/blank/COMMENTS pattern. */
function formatCommentRow(row) {
  return ["", `; ${row.text || ""}`, "", ""];
}

/** Primary/secondary stat-attr line — comma-joined flags, or "no" if none. */
function attrLine(flags) {
  const nonEmpty = flags.filter((f) => f);
  return nonEmpty.length === 0 ? "no" : nonEmpty.join(", ");
}

/** Full unit block as an array of lines. */
function formatUnit(row) {
  const out = [];
  out.push(`; COMMENTS              ${row["Name / Comments"] || row.name || ""}`);
  out.push(line("type",          row["type"]));
  out.push(line("dictionary",    row["dictionary"]));
  out.push(line("category",      row["category"]));
  out.push(line("class",         row["class"]));
  if (row["voice_type"])    out.push(line("voice_type",    row["voice_type"]));
  if (row["voice_indexes"]) out.push(line("voice_indexes", row["voice_indexes"]));
  if (row["banner fac"])    out.push(line("banner faction", row["banner fac"]));
  if (row["banner holy"])   out.push(line("banner holy",    row["banner holy"]));

  // Soldier block — either single "soldier <model>, <men>, <extras>, <mass>"
  // or "soldiers <men>, <extras>, <mass>" followed by a brace block listing
  // ethnicity models.
  const variation = Number(row["unit variation"] || 0);
  const men = row["# of men"] ?? 0;
  const extras = row["# of extras"] ?? 0;
  const mass = row["mass"] != null ? fmtNum(row["mass"]) : "";
  if (variation === 0) {
    out.push(line("soldier", joinCSV([row["model"] || "", men, extras, mass])));
  } else {
    // VBA emits these lines with keyword left-justified in the 24-char
    // column. Model names are placed at column 25 (24-space prefix) —
    // they aren't indented further than the `default` keyword; the
    // 24-char padding IS the indent. Matching this exactly so diffs
    // against OG EDU are clean.
    out.push(line("soldiers", joinCSV([men, extras, mass])));
    out.push(pad24("{"));
    out.push(pad24("    default"));
    out.push(pad24("    {"));
    for (let i = 1; i <= 7; i++) {
      const m = row[`model${i}`];
      if (m) out.push(" ".repeat(KEY_PAD) + m);
    }
    out.push(pad24("    }"));
    out.push(pad24("}"));
  }

  // Officers / ship / engine / animal / mount.
  for (let i = 1; i <= 5; i++) {
    if (row[`officer${i}`]) out.push(line("officer", row[`officer${i}`]));
  }
  if (row["ship"])   out.push(line("ship",   row["ship"]));
  if (row["engine"]) out.push(line("engine", row["engine"]));
  if (row["animal"]) out.push(line("animal", row["animal"]));
  if (row["mount"])  out.push(line("mount",  row["mount"]));

  // mount_effect: comma-separated VS bonuses. Only emit when at least
  // one of horse/elephant/chariot/camel has a value. Order is fixed.
  const vsParts = [row["vs_horse"], row["vs_elephant"], row["vs_chariot"], row["vs_camel"]].filter(Boolean);
  if (vsParts.length) out.push(line("mount_effect", vsParts.join(", ")));

  // Attributes — aggregate every boolean flag column into one comma list.
  const ATTR_COLS = [
    "sea_faring", "can_swim", "hide_forest(3)", "hide_l_grass", "can_sap",
    "frighten_f", "frighten_m", "can_amok", "gen_unit", "cant_circle/warcry/druid",
    "no_custom", "command", "merc_unit", "hardy(2)", "p_charge", "is_peas",
    "can_horde", "free_upk", "knight", "can_withdraw", "stakes", "form_charge",
    "cannot_skrm", "gunpowder", "gunmen_cav/xbow/pike/incendiary/artillery",
    "st_n_phlnx/skrm", "fire_rank", "peasant", "can/mor/roc/wag/stdr", "explode",
    "unique unit",
  ];
  const attrFlags = ATTR_COLS.map((c) => row[c]).filter((v) => v);
  if (attrFlags.length) out.push(line("attributes", attrFlags.join(", ")));

  // Formation
  const hrCl = row["h. cl. spacing"], vrCl = row["v. cl. spacing"];
  const hrLs = row["h. l. spacing"],  vrLs = row["v. l. spacing"];
  const ranks = row["ranks"];
  const formation = joinCSV([fmtNum(hrCl), fmtNum(vrCl), fmtNum(hrLs), fmtNum(vrLs), ranks, row["formation1"], row["formation2"]]);
  if (formation) out.push(line("formation", formation));

  // stat_health
  if (row["hp"] != null || row["sec hp"] != null) {
    out.push(line("stat_health", joinCSV([row["hp"] ?? 1, row["sec hp"] ?? 1])));
  }

  // stat_pri / stat_pri_attr
  out.push(line("stat_pri", joinCSV([
    row["attack"] ?? 0, row["charge"] ?? 0,
    row["msl type"] || "no", row["msl range"] ?? 0, row["msl ammo"] ?? 0,
    row["wpn type"] || "melee", row["wpn tech"] || "simple",
    row["dmg type"] || "piercing", row["sound type"] || "none",
    row["min delay"] ?? 25, fmtNum(row["lethality"] ?? 1),
  ])));
  out.push(line("stat_pri_attr", attrLine([
    row["ap"], row["bp"], row["spear-attr"], row["spear_bon"], row["pike"],
    row["prec"], row["thrown"], row["launch"], row["area"],
  ])));

  // stat_sec / stat_sec_attr (always emitted; "no" placeholder values fine)
  out.push(line("stat_sec", joinCSV([
    row["s attack"] ?? 0, row["s charge"] ?? 0,
    row["s msl type"] || "no", row["s msl range"] ?? 0, row["s msl ammo"] ?? 0,
    row["s wpn type"] || "melee", row["s wpn tech"] || "simple",
    row["s dmg type"] || "piercing", row["s sound type"] || "none",
    row["s min delay"] ?? 25, fmtNum(row["s lethality"] ?? 1),
  ])));
  out.push(line("stat_sec_attr", attrLine([
    row["s ap"], row["s bp"], row["s spear-att"], row["s spear_b"], row["s pike"],
    row["s prec"], row["s thrown"], row["s launch"], row["s area"],
  ])));

  // stat_ter (engines with a sec projectile)
  if (row["t attack"] != null) {
    out.push(line("stat_ter", joinCSV([
      row["t attack"], row["t charge"] ?? 0,
      row["t msl type"] || "no", row["t msl range"] ?? 0, row["t msl ammo"] ?? 0,
      row["t wpn type"] || "melee", row["t wpn tech"] || "simple",
      row["t dmg type"] || "piercing", row["t sound type"] || "none",
      row["t min delay"] ?? 25, fmtNum(row["t lethality"] ?? 1),
    ])));
    out.push(line("stat_ter_attr", attrLine([
      row["t ap"], row["t bp"], null, null, null, null, null,
      row["t launch"], row["t area"],
    ])));
  }

  // stat_pri_armour / stat_sec_armour
  out.push(line("stat_pri_armour", joinCSV([
    row["armour"] ?? 0, row["defence"] ?? 0, row["shield"] ?? 0,
    row["hit sound"] || "flesh",
  ])));
  out.push(line("stat_sec_armour", joinCSV([
    row["sec armour"] ?? 0, row["sec defence"] ?? 0, row["sec hit sound"] || "flesh",
  ])));

  // stat_heat / stat_ground
  out.push(line("stat_heat",    row["heat"] ?? 0));
  out.push(line("stat_ground",  joinCSV([row["scrub"] ?? 0, row["sand"] ?? 0, row["forest"] ?? 0, row["snow"] ?? 0])));

  // stat_mental
  const mentalParts = [row["morale"] ?? 1, row["discipline"] || "normal", row["training"] || "trained"];
  if (row["mrl lock"]) mentalParts.push(row["mrl lock"]);
  out.push(line("stat_mental", joinCSV(mentalParts)));

  out.push(line("stat_charge_dist", row["charge dist"] ?? 0));
  out.push(line("stat_fire_delay",  row["fire delay"] ?? 0));
  out.push(line("stat_food",        joinCSV([row["food1"] ?? 60, row["food2"] ?? 300])));

  // stat_cost
  const costParts = [
    row["turns"] ?? 1, row["price"] ?? 0, row["upkeep"] ?? 0,
    row["wpn upg"] ?? 0, row["arm upg"] ?? 0, row["cb cost"] ?? 0,
  ];
  if (row["cb unit lim"] != null) costParts.push(row["cb unit lim"]);
  if (row["cb cost pen"] != null) costParts.push(row["cb cost pen"]);
  out.push(line("stat_cost", joinCSV(costParts)));

  // Recruitment priority (emitted even when 0 is acceptable)
  if (row["recruit_priority_offset"] != null) {
    out.push(line("recruit_priority_offset", row["recruit_priority_offset"]));
  }

  // Ownership. v0.7.0 provides a pre-built string from the unit def's
  // FactionalOwnership / MercOwnership columns; older workbooks fall back
  // to the Y-flag map.
  if (row.ownershipString) {
    out.push(line("ownership", row.ownershipString));
  } else if (row.ownership) {
    const tags = Object.keys(row.ownership).filter((k) => k !== "slave");
    if (row.ownership.slave) tags.push("slave");
    if (tags.length) out.push(line("ownership", tags.join(", ")));
  }

  // Per-faction ethnicity lines (VBA Cases 204+). One line per faction
  // the unit is available to, using the unit's single ethnicity-region
  // and ethnicity-attributes values. Emits nothing when the unit has no
  // ethnicity region defined (majority of units in non-ethnicity mods).
  if (row.ethnicityRegion && row.ethnicityTags && row.ethnicityTags.length) {
    const region = row.ethnicityRegion;
    const attrs  = row.ethnicityAttributes || "";
    for (const tag of row.ethnicityTags) {
      out.push(line("ethnicity", `${tag}, ${region}, ${attrs}`));
    }
  }

  return out;
}

/**
 * Build the full EDU text for a project's computed rows.
 *
 * @param {object[]} dataRows      output of compute(project)
 * @param {import("./xlsmImporter").Project} project
 * @returns {string}                the complete EDU file text
 */
function formatEdu(dataRows, project) {
  const lines = [];
  const preamble = buildPreamble(project, project.header || []);
  for (const l of preamble) lines.push(l);

  // Multiple unit-def rows can share the same `type` (numbered variants
  // like Velites1 / Velites2 provide per-ethnicity model sets). VBA
  // writes only the first occurrence per type; later variants are
  // silently dropped. Match that behaviour so we don't emit duplicates.
  const seen = new Set();
  for (const row of dataRows) {
    if (row.kind === "wip") continue;
    if (row.kind === "comment") {
      // The "#ACTUAL EDU STARTS HERE" row at the top of UnitDefinitions
      // is a section divider; the preamble already emits it, so skip
      // the duplicate.
      if (/^actual edu starts here\s*$/i.test(String(row.text || "").trim())) continue;
      for (const l of formatCommentRow(row)) lines.push(l);
      continue;
    }
    if (row.kind !== "data") continue;
    const k = row.type ? String(row.type).toLowerCase() : `__row_${row.row}`;
    if (seen.has(k)) continue;
    seen.add(k);
    for (const l of formatUnit(row)) lines.push(l);
    lines.push("");
  }
  // The reference EDU ends with one blank line after the last unit's
  // ownership (i.e. trailing "\n" exactly once). Our loop pushes "" after
  // every unit including the final one — that already produces the
  // trailing newline when joined, so don't double up.
  while (lines.length >= 2 && lines[lines.length - 1] === "" && lines[lines.length - 2] === "") {
    lines.pop();
  }
  // VBA writes the EDU with Windows CRLF line endings; mirror that so
  // line-by-line diff tools (Notepad++ Compare, BeyondCompare, etc.)
  // don't flag every line as different on a CRLF-vs-LF mismatch.
  return lines.join("\r\n");
}

export { formatEdu, formatUnit, buildPreamble };
